# ============================================================
#  update_pm_hourly.ps1
#  ดึงค่าฝุ่น PM2.5 รายชั่วโมง (24 ชม.) ของวันล่าสุดที่ครบ ของ 4 จังหวัดเขต 7
#  จากไฟล์ GISTDA แล้วเขียนไฟล์ pm-hourly.js
#  ตั้งให้รันทุกวัน 09:00 ผ่าน Windows Task Scheduler
# ============================================================
$ErrorActionPreference = 'Stop'

$root = 'C:\Users\windows\Desktop\ศุนย์อนายที่ 7 ขอนแก่น\งานข้อมูลและติดตามประเมินผล\เมืองสุขภาพดี\งานฝุ่น PM2.5\งาน dashboard\ข้อมูลฝุ่นจาก Gisda'
$proj = 'C:\Users\windows\Desktop\pm25_extract\pm2-5-7\project'
$out  = Join-Path $proj 'pm-hourly.js'
$log  = Join-Path $proj 'update_pm_hourly.log'
function Log($m){ "$([DateTime]::Now.ToString('yyyy-MM-dd HH:mm:ss'))  $m" | Add-Content -LiteralPath $log -Encoding UTF8 }

try {
  $provs = [ordered]@{ 'ขอนแก่น'='KKN'; 'กาฬสินธุ์'='KSN'; 'มหาสารคาม'='MKM'; 'ร้อยเอ็ด'='RET' }
  $thaiYear = (Get-Date).Year + 543

  $provData = [ordered]@{}
  $dateUsed = $null

  foreach($th in $provs.Keys){
    $code = $provs[$th]
    $yearDir = Join-Path $root "$th\$thaiYear"
    $hours24 = @(); for($i=0;$i -lt 24;$i++){ $hours24 += $null }
    $picked = $null
    if(Test-Path -LiteralPath $yearDir){
      $files = Get-ChildItem -LiteralPath $yearDir -Recurse -Filter 'PM25_Province_24hrs_*.csv' -ErrorAction SilentlyContinue
      # เรียงวันที่จากใหม่ -> เก่า
      $byDate = $files | ForEach-Object {
        if($_.Name -match '(\d{4}-\d{2}-\d{2})'){ [pscustomobject]@{ date=$matches[1]; file=$_.FullName } }
      } | Sort-Object date -Descending

      foreach($entry in $byDate){
        $h = @(); for($i=0;$i -lt 24;$i++){ $h += $null }
        $cnt = 0
        Get-Content -LiteralPath $entry.file | Select-Object -Skip 1 | ForEach-Object {
          $p = $_ -split ','
          if($p.Length -ge 4){
            $v = 0.0
            $okv = [double]::TryParse($p[1], [ref]$v)
            if($okv -and $p[3] -match '\s(\d{2}):'){ $hr = [int]$matches[1]; if($hr -ge 0 -and $hr -le 23){ $h[$hr] = [math]::Round($v,1); $cnt++ } }
          }
        }
        if(-not $picked){ $hours24 = $h; $picked = $entry.date }   # เก็บล่าสุดไว้ก่อน (fallback)
        if($cnt -ge 24){ $hours24 = $h; $picked = $entry.date; break }  # เจอวันครบ 24 ชม. -> ใช้เลย
      }
    }
    # เติมช่องว่าง (ถ้ามี) ด้วยค่าก่อนหน้า เพื่อให้เส้นกราฟต่อเนื่อง
    $last = 0
    for($i=0;$i -lt 24;$i++){ if($null -eq $hours24[$i]){ $hours24[$i] = $last } else { $last = $hours24[$i] } }
    $provData[$code] = $hours24
    if($picked -and (-not $dateUsed -or $picked -gt $dateUsed)){ $dateUsed = $picked }
  }

  if(-not $dateUsed){ Log "ABORT: ไม่พบไฟล์ข้อมูลรายชั่วโมง"; exit }

  $hourLabels = @(); for($i=0;$i -lt 24;$i++){ $hourLabels += ('{0:D2}:00' -f $i) }

  $obj = [ordered]@{
    updated   = ([DateTime]::Now.ToString('yyyy-MM-dd HH:mm'))
    date      = $dateUsed
    hours     = $hourLabels
    provinces = $provData
  }
  $json = $obj | ConvertTo-Json -Depth 6
  $js   = "// PM2.5 รายชั่วโมง (24 ชม. วันล่าสุด) จากไฟล์ GISTDA - auto-generated by update_pm_hourly.ps1`r`n// อัปเดตอัตโนมัติทุกวัน 09:00 - อย่าแก้ไฟล์นี้ด้วยมือ`r`nwindow.PM_HOURLY = $json;`r`n"
  [System.IO.File]::WriteAllText($out, $js, (New-Object System.Text.UTF8Encoding($false)))
  Log "OK: pm-hourly.js updated · date $dateUsed"
}
catch {
  Log "ERROR: $($_.Exception.Message)"
}
